### ISSUE TITLE
Pull resistor and cap on HAL data line

### ISSUE THREAD

**Issue by Mynogs** [Mynogs/Issues#1]

**Comment by NilsASP** [comment]
Datasheet of the Hall Sensor says only a resistor on the HAL data line, but no capacitor. 
Should i implement only a 4K7 Pull up?

**Comment by Mynogs** [comment]
Output current of the sensor is max 30mA.
I want a strong signal so pullup is 330Ohm (10mA).
C is 47nF (1/tau = 65kHz -> 1/32 PWM frequency)

**Comment by NilsASP** [comment]
done!
