### ISSUE TITLE
Power lost timer 

### ISSUE THREAD

**Issue by Mynogs** [Mynogs/Issues#3]
Simple circuit of capacitor, resistor and MOSFET to determine the duration of the shutdown. Duration 2 seconds.

**Comment by NilsASP** [comment]
[Power_Lost_Timer.zip](https://github.com/Mynogs/Issues/files/11308584/Power_Lost_Timer.zip)

**Comment by NilsASP** [comment]
Something like this? 
With this Circuit you can detect with a normal digital GPIO if the duration was longer than 2s.
If the GPIO is LOW than the duration was longer than 2s. 

I think the LOW Level is under 2.5V, but before implementation i will check in the datasheet the exact level.

**Comment by Mynogs** [comment]
The input of the CPU always has a parasitic diode after plus. Direction of flow is to plus. So it is normally blocked and we derive from the voltage on the pin becomes greater than plus. That is what is desired.
But if the CPU is now without voltage, plus is equal to ground and the capacitor is immediately discharged.
That's why I put a MOSFET in between. It has a very high impedance at the gate. In this way, the capacitor is not discharged in an uncontrolled manner.
So please add the MOSFET.

PS
You forgot to emulate the CPU input in the simulation :-)

**Comment by NilsASP** [comment]
We are facing some problems to simulate the wished behavior. 
Mr Kramer and me are devoid of ideas. 
Could you do a simulation for us?

**Comment by Mynogs** [comment]
Yes!

**Comment by Mynogs** [comment]
Please see email!

**Comment by NilsASP** [comment]
Done!
