### ISSUE TITLE
Cleanup schematics

### ISSUE THREAD

**Issue by Mynogs** [Mynogs/Issues#7]
Text "BootMode=CAN" is wrong. "BootMode=FLASH" is correct.
inconsistent naming of the signals (GPIO18 X2 --> X2). 
Sometimes with a yellow sign, sometimes without. 
Set junctions to other components (e.g. SDA/SCL). 
Unconnected pins of the cpu without wire (GPIO30)

**Comment by NilsASP** [comment]
1. Done!
2. Done!
3. Changed where it is possible!
4. didnt find a nice solution yet
5. Done!
